# This is a basic workflow that is manually triggered

name: O nome do Workflow
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Nome da Pasta'
        # Default value if no value is explicitly provided
        default: 'app'
        # Input has to be provided for the workflow to run
        required: true
        #False significa que o input pode ser deixado em branco
        # The data type of the input
        type: string

      ambiente:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Ambiente'
        # Default value if no value is explicitly provided
        default: 'TESTE'
        # Input has to be provided for the workflow to run
        required: true
        #False significa que o input pode ser deixado em branco
        # The data type of the input
        type: string
        # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  # greet: Vamos substituir por:
  criar_pasta_job:
    # Podemos crianr quantos jobs quisermos
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Criar Pasta
      #run: echo "Hello ${{ inputs.name }}"
      run: mkdir "${{ inputs.name }}-${{ inputs.ambiente }}"
    - name: Ver a versão de Python
      run: python --version
    - name: Ver a versão de Python
      run: |
        python --version
        ls -all
        echo "print('Hello')" > hello.py
        python hello.py
